# Generated by Django 3.1 on 2024-04-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.TextField(choices=[('done', 'Done'), ('in progress', 'In Progress'), ('new', 'New')], default='new')),
            ],
        ),
    ]
